name: Mirror rolling to main

on:
  push:
    branches: [ rolling ]

jobs:
  mirror-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      with:
        target-branch: main